name = "GridSide"
license = "MIT"
licenselink = "https://github.com/rcsenkbeil/grid-side/blob/master/LICENSE.md"
description = "Personal portfolio and blog for use by the Hugo generator."
homepage = "http://rcsenkbeil.github.io/grid-side"
tags = ["blog", "portfolio", "projects"]
features = ["blog", "portfolio"]
min_version = 0.13

[author]
    name = "Chip Senkbeil"
    homepage = "http://www.senkbeil.org"

